# Generated by Django 5.2.9 on 2026-01-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=500)),
                ('query', models.TextField()),
                ('response', models.TextField()),
            ],
            options={
                'unique_together': {('case_name', 'query')},
            },
        ),
    ]
