# Generated by Django 5.2.9 on 2025-12-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=500)),
                ('citation', models.CharField(max_length=255, unique=True)),
                ('court', models.CharField(max_length=255)),
                ('date_filed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
